### ISSUE TITLE
[request] Add "show all" and "hide all" in tag settings

### ISSUE THREAD

**Issue by thesecondcomrade** [frianasoa/Ze-Notes#13]
I can't say how grateful I am for you developing this. No need for me to use Citavi or they to figure out ways to work around in Obsidian/Notify etc.. What you did is amazing. 

As you can see in the image, my settings page looks different than what you have on the notes. (Using macOS Sonoma 14.1.1 and Zotero 7.0.0-beta.53+969031a37)

So I was wondering if you can add a hide all option to the tag display area, so I don't need to go through giding them individually.

<img width="820" alt="Screenshot 2023-12-19 at 2 39 21 pm" src="https://github.com/frianasoa/Ze-Notes/assets/119909468/70100c59-d9cf-43a9-be88-014899faa522">

**Comment by frianasoa** [comment]
Hi!
Thanks for the feedback. Yes, the display has changed a lot. I did not update the README file yet. 
I have added "show all" and "hide all". You can update the plugin and try. I have added a warning because the user will lose the current setting. The following elements are always hidden by default because they are not used by the end user ["Id", "itemid", "key", "filekey"].
![image](https://github.com/frianasoa/Ze-Notes/assets/5507310/eb91da2e-c055-4d4a-a6a0-ce5e9aa287ce)

**Comment by thesecondcomrade** [comment]
Wonderful, thank you. It works like a charm.
